[package]
name = "psa-crypto"
version = "0.1.0"
authors = ["Edmund Grimley Evans <edmund.grimley-evans@arm.com>",
           "Paul Howard <paul.howard@arm.com>",
           "Ionut Mihalcea <ionut.mihalcea@arm.com>",
           "Hugues de Valon <hugues.devalon@arm.com>"]
edition = "2018"
description = "Wrapper around the PSA Cryptography API"
readme = "README.md"
keywords = ["psa", "crypto", "cryptography", "no_std"]
categories = ["api-bindings", "external-ffi-bindings", "cryptography"]
license = "Apache-2.0"
repository = "https://github.com/parallaxsecond/rust-psa-crypto"

[dependencies]
psa-crypto-sys = { path = "../psa-crypto-sys", optional = true }
log = "0.4.8"
serde = { version = "1.0.110", features = ["derive"] }

[features]
default = ["with-mbed-crypto"]
with-mbed-crypto = ["psa-crypto-sys"]
